apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: hello-world
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./clusters/linage-test/hello-world
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
