kind: Namespace
apiVersion: v1
metadata:
  name: crossplane-system
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 1m
  url: https://charts.crossplane.io/stable
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: crossplane
  namespace: crossplane-system
spec:
  interval: 10m
  releaseName: podinfo
  chart:
    spec:
      chart: crossplane 
      sourceRef:
        kind: HelmRepository
        name: crossplane
  values:
    replicaCount: 2